create table public.creators (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null unique,
  description text not null,
  "imageURL" text,
  category text not null default 'Creator',
  created_at timestamptz not null default now()
);

-- WEB103 specifically instructs students to disable RLS for this prework table.
alter table public.creators disable row level security;
alter publication supabase_realtime add table public.creators;

insert into public.creators (name, url, description, "imageURL", category) values
  ('Marques Brownlee', 'https://www.youtube.com/@mkbhd', 'Crisp, considered tech reviews that make complicated products feel immediately understandable.', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=85', 'Technology'),
  ('Simone Giertz', 'https://www.youtube.com/@simonegiertz', 'Joyfully strange engineering projects, honest experiments, and machines you never knew you needed.', 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1600&q=85', 'Making'),
  ('Jazza', 'https://www.youtube.com/@Jazza', 'Big-hearted art challenges and practical creative lessons for anyone who wants to make more things.', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1600&q=85', 'Art'),
  ('Kurzgesagt', 'https://www.youtube.com/@kurzgesagt', 'Vivid animated explainers that turn science, philosophy, and the future into irresistible stories.', 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=85', 'Science'),
  ('LockPickingLawyer', 'https://www.youtube.com/@lockpickinglawyer', 'Fast, fascinating lock breakdowns that reveal how everyday security works—and where it fails.', 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85', 'Security');
